### ISSUE TITLE
Missing leading underscores

### ISSUE THREAD

**Issue by KaratzasBasil** [nlpaueb/dc#17]
Edit: I have now made a pull request that solves this issue and fixes the README file

I just started using this package so excuse me if I'm ever mistaken in any issues that I raise.
Using the package, I get a lot of errors about function names. Browsing through the files, I saw that the actual call names of those functions have a leading underscore. I made this issue yesterday with 1 line of code but now I'm editing it to reference more:

https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/data/downloads.py#L14
(_get_logger might not need the leading underscore in dc/configuration.py, since it doesn't seem like a 'private' function from what I saw, so this line of code may be correct actually. Note that if you delete the leading underscore in dc/configuration.py, you'll also have to delete it in lines 7 and 9 of dc/evaluation/evaluation.py)

https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/evaluation/evaluation.py#L59

https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/evaluation/evaluation.py#L102

https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/evaluation/evaluation.py#L63

https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/evaluation/evaluation.py#L64

https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/evaluation/evaluation.py#L106

https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/evaluation/evaluation.py#L107

**Comment by MaryGeorgiou** [comment]
Hi Vasili,
I'm sorry for replying so late. So you are saying the get_loggerd does not need to be private? Right?
I absolutely agree I refactored it already. It will be there in the new version
This way users can change the log level easier.

**Comment by KaratzasBasil** [comment]
Hi Mary,
Yes, and I'm also referencing some lines of code that raised me errors. The problem is that the functions called there were probably edited into having a leading underscore on their name, that was not added to the corresponding function call of the lines I'm referencing. There's a big chance you also fixed this too for the new update, but in case you missed one line, I tried to proofread all the files for any wrong function calls caused by leading underscores.

**Comment by MaryGeorgiou** [comment]
Corrected, will be there in next release.
