### ISSUE TITLE
README.md issue

### ISSUE THREAD

**Issue by KaratzasBasil** [nlpaueb/dc#20]
Hello,

I think this line:
evaluation = Evaluation('iu_xray/test_images.tsv', 'results/most_frequent_word_results.tsv')
in README.md should be changed to this:
evaluation = Evaluation('results/most_frequent_word_results.tsv', 'iu_xray/test_images.tsv')

according to:
https://github.com/nlpaueb/dc/blob/211c9c70f145e71082a45376dd2cab846441023e/dc/evaluation/evaluation.py#L20

**Comment by MaryGeorgiou** [comment]
Corrected in constructor!
Thanks!!!
